version: "3.3"

services:
  app:
    container_name: jmdkh-mltb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=$DATABASE_URL
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"